[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-vercel-app.vercel.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_required_for_ssr = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

# Edge Functions configuration
[functions.daily-digest]
import_map = "./supabase/functions/import_map.json"

[functions.daily-digest.schedule]
cron = "0 1 * * *"  # Run at 1:00 AM UTC daily

[functions.embed-ticket]
import_map = "./supabase/functions/import_map.json"

[analytics]
enabled = false