[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-vercel-app.vercel.app"]
jwt_expiry = 3600

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

# Edge Functions configuration
[functions.daily-digest]

[functions.embed-ticket]

[analytics]
enabled = false